# Generated by Django 4.2.4 on 2023-10-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentrequestform",
            name="help_requested",
        ),
        migrations.AddField(
            model_name="studentrequestform",
            name="career_planning",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentrequestform",
            name="cover_letter",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentrequestform",
            name="mentor_shadowing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentrequestform",
            name="mock_interview",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentrequestform",
            name="other",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentrequestform",
            name="resume",
            field=models.BooleanField(default=False),
        ),
    ]
