# Generated by Django 4.2.4 on 2023-10-30 23:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0002_remove_studentrequestform_help_requested_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentrequestform",
            name="submission_date",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
