# Generated by Django 4.2.4 on 2023-11-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0003_studentrequestform_submission_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentrequestform",
            name="support_urgency",
            field=models.CharField(
                choices=[
                    ("within_1_week", "Within 1 Week"),
                    ("within_2_weeks", "Within 2 Weeks"),
                    ("within_1_month", "Within 1 Month"),
                    ("within_2_months", "Within 2 Months"),
                    ("no_urgent_need", "No Urgent Need"),
                ],
                default="within_1_week",
                max_length=50,
            ),
        ),
    ]
