# Generated by Django 4.2.4 on 2023-11-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0004_studentrequestform_support_urgency"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentrequestform",
            name="my_comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
