# Generated by Django 4.2.4 on 2023-11-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0005_studentrequestform_my_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentrequestform",
            name="add_comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
