# Generated by Django 4.2.4 on 2023-11-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0007_remove_studentrequestform_add_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="academic_standing",
            field=models.CharField(
                choices=[
                    ("first_year", "First Year"),
                    ("sophomore", "Sophomore"),
                    ("junior", "Junior"),
                    ("senior", "Senior"),
                    ("post_grad", "Grad Student"),
                    ("alumni", "Alum"),
                ],
                null=True,
            ),
        ),
    ]
