# Generated by Django 4.2.4 on 2024-02-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0010_remove_studentrequestform_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentrequestform",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
